#!/bin/bash
#PBS -N BWA_indexing
#PBS -o BWA_indexing.out
#PBS -l walltime=20:00:00
#PBS -l mem= g
#PBS -r n

TIMESTAMP=$(date +%Y-%m-%d_%Hh%Mm%Ss)
SCRIPT=$0
NAME=$(basename $0)


# Global variables

BWA=Path/to/executables
FASTA=/Path to genome.fasta

# index the transcriptome
$BWA/bwa index $FASTA

