#!/bin/bash
#PBS -N BWA_indexing
#PBS -o BWA_indexing.out
#PBS -l walltime=20:00:00
#PBS -l mem= g
#PBS -r n

TIMESTAMP=$(date +%Y-%m-%d_%Hh%Mm%Ss)

# Global variables
DATADIRECTORY=/Path/to/your/copy/of/WGS_pipeline
BWA=Path/to/executables
FASTA=01_info_files

# index the transcriptome
$BWA/bwa index $FASTA/name_of_genome.fasta

